const express = require("express")
const { colorRoutes } = require("./color.route")
const { materialRoutes } = require("./material.route")
const { productRoutes } = require("./product.route")
const { categoryRoutes } = require("./category.route")
const { chooseRoutes } = require("./choose.route")
const { faqRoutes } = require("./faq.route")
const { contactEnquiryRoutes } = require("./contactEnquiry.route")
const { coupounRoutes } = require("./coupoun.route")
const { newsletterRoutes } = require("./newsletter.route")
const { sliderRoutes } = require("./slider.route")
const { subCategoryRoutes } = require("./subCategory.route")
const { subSubCategoryRoutes } = require("./subSubCategory.route")
const { testimonialRoutes } = require("./testimonial.route")
const { countryRoutes } = require("./country.route")
const { dashboardAdminRoutes } = require("./dashboardAdmin.route")

const adminRoutes = express.Router()

adminRoutes.use("/country", countryRoutes)
adminRoutes.use("/color", colorRoutes)
adminRoutes.use("/material", materialRoutes)
adminRoutes.use("/product", productRoutes)
adminRoutes.use("/category", categoryRoutes)
adminRoutes.use("/choose", chooseRoutes)
adminRoutes.use("/faq", faqRoutes)
adminRoutes.use("/contactenquiry", contactEnquiryRoutes)
adminRoutes.use("/coupoun", coupounRoutes)
adminRoutes.use("/newsletter", newsletterRoutes)
adminRoutes.use("/slider", sliderRoutes)
adminRoutes.use("/subcategory", subCategoryRoutes)
adminRoutes.use("/subsubcategory", subSubCategoryRoutes)
adminRoutes.use("/testimonial", testimonialRoutes)
adminRoutes.use("/dashboardadmin", dashboardAdminRoutes)

module.exports = { adminRoutes }